[build-system]
requires = ["poetry >= 0.12, <1"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "my_site"
version = "0.1.0"
description = ""
authors = ["Guido Avvisati <guido.avvisati@gmail.com>"]